export class StorageQueryService {
  loading = { set: () => {}, value: false };
  loaded = { set: () => {}, value: false };
  lastLoaded = { set: () => {}, value: null };
  allProfiles = { set: () => {}, value: [] };
  user = { set: () => {}, value: null };
  dailyActivities = { set: () => {}, value: [] };
  isEntityLoading = () => false;
  findById = () => undefined;
  query = () => [];
  setCollection = () => {};
  setCollectionByTable = () => {};
  setLoaded = () => {};
  setLastLoaded = () => {};
  setAllProfiles = () => {};
  setUser = () => {};
  setDailyActivities = () => {};
  loadInitialData = () => Promise.resolve();
  loadMoreData = () => Promise.resolve();
  loadAdminData = () => Promise.resolve();
  loadMoreTodos = () => Promise.resolve();
  loadMoreTasks = () => Promise.resolve();
  loadMoreSubtasks = () => Promise.resolve();
  loadMoreComments = () => Promise.resolve();
  loadMoreCategories = () => Promise.resolve();
  loadMoreChats = () => Promise.resolve();
  ensureTodosLoaded = () => Promise.resolve();
  ensureTasksLoaded = () => Promise.resolve();
  ensureSubtasksLoaded = () => Promise.resolve();
  ensureChatsLoaded = () => Promise.resolve();
  ensureCategoriesLoaded = () => Promise.resolve();
  ensureTaskCommentsLoaded = () => Promise.resolve();
  ensureSubtaskCommentsLoaded = () => Promise.resolve();
  ensureCommentsLoaded = () => Promise.resolve();
  ensureUserLoaded = () => Promise.resolve();
  ensureProfileLoaded = () => Promise.resolve();
  ensurePublicProfilesLoaded = () => Promise.resolve();
  getTodosByVisibility = () => [];
  getTodosWithNestedTasks = () => [];
  getTasksWithNestedSubtasks = () => [];
  getSubtasksWithNestedComments = () => [];
  getUnreadChatCount = () => 0;
  getUsername = () => "";
  subtaskExists = () => false;
  subtaskCountByTaskId = () => 0;
  isPrivateData = () => false;
  canAccessOffline = () => true;
  isCacheValid = () => true;
}
