#[path = "admin.command.rs"]
pub mod admin_command;
#[path = "archive.command.rs"]
pub mod archive_command;
#[path = "auth.command.rs"]
pub mod auth_command;
#[path = "crud_command.rs"]
pub mod crud_command;
#[path = "group.command.rs"]
pub mod group_command;
#[path = "macros.rs"]
pub mod macros;
#[path = "room.command.rs"]
pub mod room_command;
#[path = "schema.command.rs"]
pub mod schema_command;
#[path = "stats.command.rs"]
pub mod stats_command;
#[path = "subtask.command.rs"]
pub mod subtask_command;
#[path = "todo.command.rs"]
pub mod todo_command;
#[path = "update.command.rs"]
pub mod update_command;
