#[path = "auth_data_sync.service.rs"]
pub mod auth_data_sync;
#[path = "auth_login.auth.service.rs"]
pub mod auth_login;
#[path = "auth_password.auth.service.rs"]
pub mod auth_password;
#[path = "auth_qr.auth.service.rs"]
pub mod auth_qr;
#[path = "auth_register.auth.service.rs"]
pub mod auth_register;
#[path = "auth_token.auth.service.rs"]
pub mod auth_token;
#[path = "auth_totp.auth.service.rs"]
pub mod auth_totp;
