#[path = "auth_data_sync.service.rs"]
pub mod auth_data_sync;
#[path = "auth-login.service.rs"]
pub mod auth_login;
#[path = "auth-password.service.rs"]
pub mod auth_password;
#[path = "auth-qr.service.rs"]
pub mod auth_qr;
#[path = "auth-register.service.rs"]
pub mod auth_register;
#[path = "auth-token.service.rs"]
pub mod auth_token;
#[path = "auth-totp.service.rs"]
pub mod auth_totp;
