// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CategoryItem { name: string, count: number, percentage: number, color: string, }