// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryItem } from "./CategoryItem";
import type { CompletionTrendItem } from "./CompletionTrendItem";
import type { DailyActivityItem } from "./DailyActivityItem";

export interface ChartDataModel { completionTrend: Array<CompletionTrendItem>, categories: Array<CategoryItem>, dailyActivity: Array<DailyActivityItem>, }