// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DetailedMetricModel { name: string, current: string, previous: string, change: number, }