// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EmailConfig { smtpUsername: string, smtpPassword: string, smtpServer: string, smtpPort: number, resetTokenExpiryHours: bigint, }