// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StatisticsModel { totalTasks: number, completionRate: number, averageTaskTime: number, productivityScore: number, previousTotalTasks: number, previousCompletionRate: number, previousAverageTime: number, previousProductivityScore: number, }