// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartDataModel } from "./ChartDataModel";
import type { DetailedMetricModel } from "./DetailedMetricModel";
import type { StatisticsModel } from "./StatisticsModel";

export interface StatisticsResponseModel { statistics: StatisticsModel, chartData: ChartDataModel, detailedMetrics: Array<DetailedMetricModel>, }