#[path = "category.entity.rs"]
pub mod category_entity;
#[path = "chat.entity.rs"]
pub mod chat_entity;
#[path = "comment.entity.rs"]
pub mod comment_entity;
#[path = "daily_activity.entity.rs"]
pub mod daily_activity_entity;
#[path = "email_config.entity.rs"]
pub mod email_config;
#[path = "login_form.entity.rs"]
pub mod login_form_entity;
#[path = "password_reset.entity.rs"]
pub mod password_reset;
#[path = "profile.entity.rs"]
pub mod profile_entity;
#[path = "provider_type.entity.rs"]
pub mod provider_type_entity;
#[path = "relation_config.entity.rs"]
pub mod relation_config;
#[path = "relation_obj.entity.rs"]
pub mod relation_obj;
#[path = "response.entity.rs"]
pub mod response_entity;
#[path = "signup_form.entity.rs"]
pub mod signup_form_entity;
#[path = "statistics.entity.rs"]
pub mod statistics_entity;
#[path = "subtask.entity.rs"]
pub mod subtask_entity;
#[path = "sync_metadata.entity.rs"]
pub mod sync_metadata_entity;
#[path = "table.entity.rs"]
pub mod table_entity;
#[path = "task.entity.rs"]
pub mod task_entity;
#[path = "todo.entity.rs"]
pub mod todo_entity;
#[path = "traits.entity.rs"]
pub mod traits;
#[path = "user.entity.rs"]
pub mod user_entity;
#[path = "websocket.entity.rs"]
pub mod websocket_entity;
