#[path = "category.model.rs"]
pub mod category_model;
#[path = "daily_activity.model.rs"]
pub mod daily_activity_model;
#[path = "email_config.model.rs"]
pub mod email_config;
#[path = "login_form.model.rs"]
pub mod login_form_model;
#[path = "password_reset.model.rs"]
pub mod password_reset;
#[path = "profile.model.rs"]
pub mod profile_model;
#[path = "relation_obj.model.rs"]
pub mod relation_obj;
#[path = "response.model.rs"]
pub mod response_model;
#[path = "signup_form.model.rs"]
pub mod signup_form_model;
#[path = "statistics.model.rs"]
pub mod statistics_model;
#[path = "subtask.model.rs"]
pub mod subtask_model;
#[path = "task.model.rs"]
pub mod task_model;
#[path = "task_shares.model.rs"]
pub mod task_shares_model;
#[path = "todo.model.rs"]
pub mod todo_model;
#[path = "user.model.rs"]
pub mod user_model;
